server.port=8080
spring.profiles.active=local

services.users.url=${USERS_SERVICE_URL}
services.payments.url=${PAYMENTS_SERVICE_URL}
services.orders.url=${ORDERS_SERVICE_URL}

spring.thymeleaf.cache=false
services.shipping.url=${SHIPPING_SERVICE_URL}
